# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Connect4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Connect4
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'


  target 'Connect4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
